server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: master #presentacion3 #nomnbre de la rama actual
          uri: https://github.com/CleverSalvador/config-data
          search-paths: / #config-data
  security:
    user:
      name: root
      password: s3cr3t

  application:
    name: config-service


